[platformio]
default_envs = main_controller

[env]
platform = atmelavr
framework = arduino
monitor_speed = 9600

[env:main_controller]
board = megaatmega2560
build_src_filter =
  +<main_controller.cpp>
  -<obstacle_detection_uno.cpp>

[env:obstacle_detection_uno]
board = uno
build_src_filter =
  +<obstacle_detection_uno.cpp>
  -<main_controller.cpp>
